FROM java:8
MAINTAINER suaytian
VOLUME /tmp
ADD springcloud-tian-admin-1.0-SNAPSHOT.jar app.jar
CMD echo "springcloud-tian-admin 启动"
#ENV ACTIVE spring.profiles.active=pro
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","app.jar","--spring.profiles.active=pro"]
EXPOSE 9004