server:
  port: 80

spring:
  application:
    name: springcloud-tian-consumer
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/,http://eureka7003:7003/eureka/
    register-with-eureka: false
feign:
  hystrix:
    enabled: true #开启服务降级

logging:
  level:
    com:
      tian:
        springcloud: debug