server:
  port: 8002

spring:
  application:
    name: springcloud-tian-consumer
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
logging:
  level:
    com:
      tian:
        springcloud: debug
