server:
  port: 80

spring:
  application:
    name: springcloud-tian-consumer

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com:
      tian:
        springcloud: debug