spring:
  application:
    name: springcloud-tian-eureka
  profiles:
    active: dev
    #include:
      #- pro
      #- peer3

---
server:
  port: 7001
spring:
  profiles: pro
eureka:
  instance:
    hostname: eureka${server.port} #配置了host映射
    #如果register-with-eureka为false 则服务每分钟向注册中心续订的最大阈值计算公式为2*(n+1)*计算因子 默认0.85
    #如果register-with-eureka为true  则服务每分钟向注册中心续订的最大阈值计算公式为2*n*计算因子 n为服务个数
    #服务向注册中心续订的周期时间设置 默认是30s 则每个服务向注册中心续订的次数为每分钟2次
    #if 服务个数*最近一分钟续订次数 <= 最大阈值 自我保护机制将被激活
    #比如 2*60/30 = 4 < 2*(2+1)*0.85 = 5.1 ≈ 5 得出结论 4<5 自我保护机制激活
    lease-renewal-interval-in-seconds: 30
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/,http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    #阈值计算因子 默认0.85
    renewal-percent-threshold: 0.85
    #自我保护机制 默认开启
    enable-self-preservation: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
---
server:
  port: 7002
spring:
  profiles: dev
eureka:
  instance:
    hostname: eureka7002 #配置了host映射
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7003:7003/eureka/
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
---
server:
  port: 7003

spring:
  profiles: test
eureka:
  instance:
    hostname: eureka7003 #配置了host映射
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"