server:
  port: 9004

spring:
  application:
    name: admin
  #mail: #spring boot admin异常邮件通知
    #host: smtp.163.com
    #username:
    #password:
  #boot:
    #admin:
      #notify:
        #mail:
          #to:

eureka:
  instance:
    prefer-ip-address: true
    health-check-url-path: /actuator/health
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/,http://eureka7003:7003/eureka/


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
