FROM java:8
MAINTAINER suaytian
VOLUME /tmp
ADD springcloud-tian-eureka-server-1.0-SNAPSHOT.jar app.jar
CMD echo "springcloud-tian-eureka-server 启动"
#ENV ACTIVE spring.profiles.active=pro
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","app.jar","--spring.profiles.active=pro"]
EXPOSE 7001