spring:
  application:
    name: config-server
  security:
    user:
      name: admin
      password: 123456
server:
  port: 9003

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"