server:
  port: 8001
spring:
  application:
    name: springcloud-tian-user

management: #暴露健康检查web接口
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    com:
      tian:
        springcloud: debug