server:
  port: 7003

spring:
  application:
    name: springcloud-tian-eureka-server-03
eureka:
  instance:
    hostname: eureka7003 #配置了host映射
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/
